#ifndef __APP_BOOT_H
#define __APP_BOOT_H


#define  	APP_FLASH_ADDR	0x00004000
#define 	APP_START		0x00004200
//bootloader version 1.0
#define BOOTLOADER_VERSION	    		0x0010

//bootloader 信息
#define FLASH_STARD_ADDR				0x00004000  			//flash基地址
#define BOOTLOADER_STARD_ADDR	    	0x00002000  	
#define BOOTLOADER_END_ADDR	    		0x00003fff  			//bootloader结束地址
#define BOOTLOADER_CONFG_ADDR	    	0x00003800  			//配置空间大小0xFF


#define BOOTLOADER_INITFLAG_ADDR		BOOTLOADER_CONFG_ADDR
#define BOOTLOADER_INITFLAG_ADDR_LEN	1 

#define BOOTLOADER_VERSION_ADDR			(BOOTLOADER_INITFLAG_ADDR + BOOTLOADER_INITFLAG_ADDR_LEN)
#define BOOTLOADER_VERSION_ADDR_LEN		2     

#define BOOTLOADER_FLAG_ADDR			(BOOTLOADER_VERSION_ADDR + BOOTLOADER_VERSION_ADDR_LEN)
#define BOOTLOADER_FLAG_ADDR_LEN		1 

#define BOOTLOADER_KEY_FLAG_ADDR 		(BOOTLOADER_FLAG_ADDR + BOOTLOADER_FLAG_ADDR_LEN)
#define BOOTLOADER_KEY_FLAG_ADDR_LEN	1

#define BOOTLOADER_KEY_ADDR 			(BOOTLOADER_KEY_FLAG_ADDR + BOOTLOADER_KEY_FLAG_ADDR_LEN)
#define BOOTLOADER_KEY_ADDR_LEN			16	// 3des,2key
//操作返回码
#define SW_OPERATION_SUCCESS	0x9000
#define SW_MAC_ERROR			0x6982
#define SW_P1P2_ERROR			0x6a86//P1 P2不正确
#define SW_MEMORY_ERROR			0X6581 //存储器故障
#define SW_MEMORY_BEYOND		0X6582 //存储器越界
#define SW_VERIFY_CRC_ERROR		0X7000 //存储器越界

//命令码
//#define CMD_DNLOAD_DATA_A		0x10
#define CMD_DNLOAD_DATA_B		0x11
#define CMD_UPLOAD_DATA		0x12
#define CMD_BOOT_CRC			0x13
#define CMD_ERASE_SECTOR		0x14
#define CMD_BOOT_FLAG 			0x3c
#define CMD_BOOT_INFO			0xF9
#define CMD_BOOT_DNLOAD_KEY 	0xFB
#define READ_TERMINAL_INFO		0x10

//设备相关信息
#define DEVICE_INFO_START_ADDR	0x00038000									//设备信息地址
#define DEVICE_INFO_END_ADDR	0x00038800-1								//设备信息地址
#define DEVICE_INFO_LEN			0x800										//设备信息长度

#define	CONFIG_FLAG				DEVICE_INFO_START_ADDR						//配置信息标识地址
#define	CONFIG_INFO_FLAG_LEN	6											//配置信息长度
#define CARDLOCKFLAG			CONFIG_FLAG + CONFIG_INFO_FLAG_LEN			//卡锁定标识地址
#define CARDLOCKFLAG_LEN		1											//卡锁定标识长度
#define	TRANSFERCODERETRY		CARDLOCKFLAG+CARDLOCKFLAG_LEN				//传输密钥重试次数地址
#define	TRANSFERCODERETRY_LEN	1											//传输密钥重试次数长度
#define	TRANSFERCODE			TRANSFERCODERETRY + TRANSFERCODERETRY_LEN	//传输密钥地址
#define	TRANSFERCODE_LEN		8											//传输密钥长度
#define DEV_INFO				TRANSFERCODE + TRANSFERCODE_LEN				//设备信息
#define DEV_INFO_LEN			116

#define COS_VER					"1.0.0.0"
#define DEV_TYPE				"ZFT1.03"

#endif __APP_BOOT_H
